package com.parallelsymmetry.dalton;

public enum WeatherDatumIdentifier {

	TEMPERATURE,
	HUMIDITY,
	PRESSURE,
	PRESSURE_TREND,
	DEW_POINT,
	WIND_DIRECTION,
	WIND_SPEED_CURRENT,
	WIND_SPEED_2_MIN_MIN,
	WIND_SPEED_2_MIN_AVG,
	WIND_SPEED_2_MIN_MAX,
	WIND_SPEED_10_MIN_MIN,
	WIND_SPEED_10_MIN_AVG,
	WIND_SPEED_10_MIN_MAX,
	RAIN_RATE,
	RAIN_TOTAL_DAILY,
	TEMPERATURE_INSIDE,
	HUMIDITY_INSIDE

}
