package com.parallelsymmetry.dalton;

public enum WeatherDatumIdentifier {

	TEMPERATURE,
	HUMIDITY,
	PRESSURE,
	DEW_POINT,
	WIND_DIRECTION,
	WIND_SPEED_INSTANT,
	WIND_SPEED_SUSTAIN,
	RAIN_RATE,
	RAIN_TOTAL_DAILY,
	TEMPERATURE_INSIDE,
	HUMIDITY_INSIDE

}
