package com.parallelsymmetry.dalton;

public enum WeatherDatumIdentifier {

	TIMESTAMP,
	TEMPERATURE,
	HUMIDITY,
	PRESSURE,
	DEW_POINT,
	WIND_CHILL,
	HEAT_INDEX,
	RAIN_RATE,
	RAIN_TOTAL_DAILY,
	WIND_DIRECTION,
	WIND_SPEED,
	WIND_SPEED_1_MIN_MIN,
	WIND_SPEED_1_MIN_AVG,
	WIND_SPEED_1_MIN_MAX,
	WIND_SPEED_2_MIN_MIN,
	WIND_SPEED_2_MIN_AVG,
	WIND_SPEED_2_MIN_MAX,
	WIND_SPEED_5_MIN_MIN,
	WIND_SPEED_5_MIN_AVG,
	WIND_SPEED_5_MIN_MAX,
	WIND_SPEED_10_MIN_MIN,
	WIND_SPEED_10_MIN_AVG,
	WIND_SPEED_10_MIN_MAX,
	WIND_DIRECTION_10_MIN_AVG,
	WIND_DIRECTION_2_MIN_AVG,
	TEMPERATURE_TREND,
	HUMIDITY_TREND,
	PRESSURE_TREND,
	WIND_SPEED_TREND,
	TEMPERATURE_INSIDE,
	HUMIDITY_INSIDE

}
